<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new item';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('item', array('action' => 'add')));
$form->prepare();?>

<table class="table table-striped">

    <?php echo $this->form()->openTag($form);?>
    <tr><td><?php echo $this->formRow($form->get('item_no'));?></td><td></td></tr>
    <tr><td><?php echo $this->formRow($form->get('name'));?></td>
    <tr><td><?php echo $this->formRow($form->get('description'));?></td>
    <td><?php echo $this->formSubmit($form->get('submit'));?></td></tr>
    <?php echo $this->form()->closeTag();?>


</table>