<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Item';
$this->headTitle($title);
?>
<html>
<body>
<div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('item', array('action' => 'add')));
    $form->prepare();?>



    <?php echo $this->form()->openTag($form); ?>
    <div class="panel panel-primary col-lg-6 col-md-6 col-lg-push-3 col-md-push-3">
        <div class="panel-body">
            <div> <?php echo $this->formRow($form->get('item_no')); ?>  </div>
            <div> <?php echo $this->formRow($form->get('name')); ?>  </div>
            <div> <?php echo $this->formRow($form->get('description')); ?>  </div>
            <div><?php echo $this->formSubmit($form->get('submit')); ?></div>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div>
</body>
</html>


