<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Item';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'item',
    array(
        'action' => 'edit',
        'id'     => $this->item_no,
    )
));
$form->prepare();

echo $this->form()->openTag($form);?>
<div class="panel panel-primary">
    <div class="panel-body">
        <div><?php echo $this->formHidden($form->get('item_no')); ?></div>
        <div><b><?php echo 'Item Number : ' , $this->item_no , ' '; ?></b></div>
        <div><?php echo $this->formRow($form->get('name')); ?></div>
        <div><?php echo $this->formRow($form->get('description')); ?></div>
        <div><?php echo $this->formSubmit($form->get('submit')); ?></div>
        <div><?php  ?></div>
    </div>
</div>





echo $this->form()->closeTag();