<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new customer';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('CID'));
echo $this->formRow($form->get('customer_type'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('middle_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('po_box'));
echo $this->formRow($form->get('street'));
echo $this->formRow($form->get('city'));
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('brn'));
echo $this->formRow($form->get('trn'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('credit_limit'));
echo $this->formRow($form->get('credit_balance'));
echo $this->formRow($form->get('emp_id'));
echo $this->formSubmit($form->get('submit'));

//Start JS
//Inline script for the customer_type select element

$this->inlineScript()->captureStart();
echo <<<JS
    //form load
    var dropdown = document.getElementById("customer_type");
    var selected = dropdown.options[dropdown.selectedIndex].text;
    if (selected == "Large Order"){
    $(".largeorder").show();
    $(".vip").hide();
    $(".mailorder").hide();
    $(".largeordervip").show();
    $(".mailordervip").hide();
    }
    if (selected == "Mail Order"){
    $(".largeorder").hide();
    $(".vip").hide();
    $(".mailorder").show();
    $(".largeordervip").hide();
    $(".mailordervip").show();
    }
    if (selected == "VIP"){
    $(".largeorder").hide();
    $(".vip").show();
    $(".mailorder").hide();
    $(".largeordervip").show();
    $(".mailordervip").show();
    }



    //dropdown menu change
    $('#customer_type').change(function(){
        var dropdown = document.getElementById("customer_type");
        var selected = dropdown.options[dropdown.selectedIndex].text;
        if (selected == "Large Order"){
        $(".largeorder").show();
        $(".vip").hide();
        $(".mailorder").hide();
        $(".largeordervip").show();
        $(".mailordervip").hide();
        }
        if (selected == "Mail Order"){
        $(".largeorder").hide();
        $(".vip").hide();
        $(".mailorder").show();
        $(".largeordervip").hide();
        $(".mailordervip").show();
        }
        if (selected == "VIP"){
        $(".largeorder").hide();
        $(".vip").show();
        $(".mailorder").hide();
        $(".largeordervip").show();
        $(".mailordervip").show();
        }
    });
JS;

$this->inlineScript()->captureEnd();
//End JS



echo $this->form()->closeTag();
