<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Customer';
$this->headTitle($title);
?>
<html>
<body>
<div class="container col-lg-10 col-md-10 col-md-push-1 col-lg-push-1">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('customer', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <div class="panel panel-primary col-lg-8 col-lg-push-2 col-md-push-2">
            <div class="panel-body">
                <div><?php echo $this->formRow($form->get('CID')); ?></div>
                <div><?php echo $this->formRow($form->get('customer_type')); ?></div>
                <div><?php echo $this->formRow($form->get('first_name')); ?></div>
                <div><?php echo $this->formRow($form->get('middle_name')); ?></div>
                <div><?php echo $this->formRow($form->get('last_name')); ?></div>
                <div><?php echo $this->formRow($form->get('po_box')); ?></div>
                <div><?php echo $this->formRow($form->get('street')); ?></div>
                <div><?php echo $this->formRow($form->get('city')); ?></div>
                <div><?php echo $this->formRow($form->get('id')); ?></div>
                <div><?php echo $this->formRow($form->get('brn')); ?></div>
                <div><?php echo $this->formRow($form->get('trn')); ?></div>
                <div><?php echo $this->formRow($form->get('email')); ?></div>
                <div><?php echo $this->formRow($form->get('credit_limit')); ?></div>
                <div><?php echo $this->formRow($form->get('credit_balance')); ?></div>
                <div><?php echo $this->formRow($form->get('emp_id')); ?></div>
                <div><?php echo $this->formSubmit($form->get('submit')); ?></div>
            </div>
        </div>


        <?php
        //Start JS
        //Inline script for the customer_type select element

        $this->inlineScript()->captureStart();
        echo <<<JS
    //form load
    var dropdown = document.getElementById("customer_type");
    var selected = dropdown.options[dropdown.selectedIndex].text;
    if (selected == "Large Order"){
    $(".largeorder").show();
    $(".vip").hide();
    $(".mailorder").hide();
    $(".largeordervip").show();
    $(".mailordervip").hide();
    }
    if (selected == "Mail Order"){
    $(".largeorder").hide();
    $(".vip").hide();
    $(".mailorder").show();
    $(".largeordervip").hide();
    $(".mailordervip").show();
    }
    if (selected == "VIP"){
    $(".largeorder").hide();
    $(".vip").show();
    $(".mailorder").hide();
    $(".largeordervip").show();
    $(".mailordervip").show();
    }



    //dropdown menu change
    $('#customer_type').change(function(){
        var dropdown = document.getElementById("customer_type");
        var selected = dropdown.options[dropdown.selectedIndex].text;
        if (selected == "Large Order"){
        $(".largeorder").show();
        $(".vip").hide();
        $(".mailorder").hide();
        $(".largeordervip").show();
        $(".mailordervip").hide();
        }
        if (selected == "Mail Order"){
        $(".largeorder").hide();
        $(".vip").hide();
        $(".mailorder").show();
        $(".largeordervip").hide();
        $(".mailordervip").show();
        }
        if (selected == "VIP"){
        $(".largeorder").hide();
        $(".vip").show();
        $(".mailorder").hide();
        $(".largeordervip").show();
        $(".mailordervip").show();
        }
    });
JS;

        $this->inlineScript()->captureEnd();
        //End JS


        echo $this->form()->closeTag();?>
    </div>

</div>
</body>
</html>
