<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete Customer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    <b>'<?php echo $this->escapeHtml($customer->first_name); ?>'</b>?
</p>
<?php
$url = $this->url('customer', array(
    'action' => 'delete',
    'id'     => $this->CID,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input class="btn btn-danger" type="submit" name="del" value="Yes" />
        <input class="btn btn-default" type="submit" name="del" value="No" />
    </div>
</form>