<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit customer';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'customer',
    array(
        'action' => 'edit',
        'id'     => $this->CID,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('CID'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('middle_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('po_box'));
echo $this->formRow($form->get('street'));
echo $this->formRow($form->get('city'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>

<table class="table table-striped">
<tr><th>Contact Numbers</th><td></td></tr>
<?php foreach ($contacts as $contact) : ?>

    <tr>
        <td><?php echo $this->escapeHtml($contact->contact_no); ?></td>
        <td>
            <form method="post">
                <input type="hidden" name="selectedNum" value="<?php echo $this->escapeHtml($contact->contact_no);?>">
                <input type="hidden" name="clickedDel" value="YES">
                <input type="submit" value = "delete">
            </form>
        </td>

    </tr>
<?php endforeach; ?>
<tr><td>
        <form method="post">
            <input type="text" name="contact">
    </td><td>
        <input class="btn btn-primary btn-sm" type="submit" name="saveClicked" value = "Save">
        </form>
    </td>
</tr>
</table>
