<?php
// module/Album/view/album/album/index.phtml:

$title = 'Customers';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('customer', array('action'=>'add'));?>">Add new customer</a>
</p>

<table class="table">

    <tr>
        <th>CID</th>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Last Name</th>
        <th>PO Box</th>
        <th>Street</th>
        <th>City</th>

    </tr>
    <?php foreach ($customers as $customer) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($customer->CID);?></td>
            <td><?php echo $this->escapeHtml($customer->first_name);?></td>
            <td><?php echo $this->escapeHtml($customer->middle_name);?></td>
            <td><?php echo $this->escapeHtml($customer->last_name);?></td>
            <td><?php echo $this->escapeHtml($customer->po_box);?></td>
            <td><?php echo $this->escapeHtml($customer->street);?></td>
            <td><?php echo $this->escapeHtml($customer->city);?></td>
            <td>
                <a href="<?php echo $this->url('customer',
                    array('action'=>'edit', 'id' => $customer->CID));?>">Edit</a>
                <a href="<?php echo $this->url('customer',
                    array('action'=>'delete', 'id' => $customer->CID));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>