<html>
<head>
    <?php
    use Album\Controller\Chart;

    $chart = new Chart('PieChart');
    $data = array(
        array('type' => 'Mail Order', 'amount' => 2),
        array('type' => 'Large Order', 'amount' => 1),
        array('type' => 'Retail Order', 'amount' => 4)
    );
    $chart->load($data, 'array');
    $options = array('title' => 'Orders', 'is3D' => true, 'width' =>750, 'height' => 600);
    echo $chart->draw('my_div', $options);
    ?>
</head>
<body>
<div id="my_div"></div>
</body>
</html>