<?php

$title = 'Statistics';
$this->headTitle($title);
?>
<div class="container col-lg-10 col-md-10 col-md-push-1 col-lg-push-1">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <hr>
    <div class=" col-lg-6 col-md-6 col-md-push-3 col-lg-push-3">
        <ul class="list-group ">
            <li class="list-group-item"><a
                    href="<?php echo $this->url('chart', array('action' => 'orderDist')) ?>"><?php echo $this->translate('Orders Distribution') ?></a>
            </li>
            <li class="list-group-item"><a
                    href="<?php echo $this->url('chart', array('action' => 'customerDist')) ?>"><?php echo $this->translate('Customers Distribution') ?></a>
            </li>
            <li class="list-group-item"><a
                    href="<?php echo $this->url('chart', array('action' => 'priceVariation')) ?>"><?php echo $this->translate('Prices Variation') ?></a>
            </li>
            <li class="list-group-item"><a
                    href="<?php echo $this->url('chart', array('action' => 'orderTimeline')) ?>"><?php echo $this->translate('Daily Sales') ?></a>
            </li>

        </ul>
    </div>
</div>