<?php


$title = 'Daily Sales';
$this->headTitle($title);
?>
<html>
<body>
<div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
    <div class="row">
        <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9"><h1><?php echo $this->escapeHtml($title); ?></h1></div>


        <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
            <h1>
                <a href="<?php echo $this->url('chart'); ?>"><input type="button"
                                                                    class="btn btn-primary btn-lg pull-right btn-block"
                                                                    value="Back"></a></h1>
        </div>
    </div>

    <div class="col-lg-8 col-md-8 col-lg-push-2 col-md-push-2" id="my_div"></div>
</div>
</body>
</html>


