<?php

$title = 'Price Variation of Item';
$this->headTitle($title);
?>
<html>
<body>
<div class="container col-lg-10 col-md-10 col-md-push-1 col-lg-push-1">
    <div class="row">
        <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9"><h1><?php echo $this->escapeHtml($title); ?></h1></div>


        <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
            <h1>
                <a href="<?php echo $this->url('chart'); ?>"><input type="button"
                                                                    class="btn btn-primary btn-lg pull-right btn-block"
                                                                    value="Back"></a></h1>
        </div>
    </div>
    <hr>

    <form method="post">
        <select name="item">
            <?php foreach ($items as $item){ ?>
                <option value="<?php echo $this->escapeHtml($item->item_no); ?>">
                    <?php echo $this->escapeHtml($item->name); ?>
                </option>
            <?php } ?>
        </select>
        </td>

        <td>
            <input class="btn btn-primary btn-sm" type="submit" name="showClicked" value = "show">
    </form>

    <?php
    use Album\Controller\Chart;

    $chart = new Chart($type);

    $chart->load($data, 'array');
    $options = array('title' => 'Price Variation of '.$_POST["item"], 'is3D' => true, 'width' => 750, 'height' => 600);
    echo $chart->draw('my_div', $options);
    ?>

    <div id="my_div"></div>


</div>
</body>
</html>

