<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Personal Representative';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('psr', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);?>

<div ><?php echo $this->formRow($form->get('emp_id')); ?></div>
<div><?php echo $this->formRow($form->get('name')); ?></div>
<div><?php echo $this->formRow($form->get('po_box')); ?></div>
<div><?php echo $this->formRow($form->get('street')); ?></div>
<div><?php echo $this->formRow($form->get('city')); ?></div>
<div ></div><?php echo $this->formSubmit($form->get('submit')); ?></div>



<?php

echo $this->form()->closeTag();