<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Personal Sales Representative';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'psr',
    array(
        'action' => 'edit',
        'id'     => $this->emp_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);?>
<div class="panel panel-primary">
    <div class="panel-body">
        <div><?php echo $this->formRow($form->get('emp_id')); ?></div>
        <div><?php echo $this->formRow($form->get('name')); ?></div>
        <div><?php echo $this->formRow($form->get('po_box')); ?></div>
        <div><?php echo $this->formRow($form->get('street')); ?></div>
        <div><?php echo $this->formRow($form->get('city'));?></div>
        <div><?php echo $this->formSubmit($form->get('submit')); ?></div>
    </div>
</div>
<?php
echo $this->form()->closeTag(); ?>

<br>
<table class="table table-striped">
    <tr><th>Contact Numbers</th><td></td></tr>
    <?php foreach ($contacts as $contact) : ?>

        <tr>
            <td><?php echo $this->escapeHtml($contact->contact_no); ?></td>
            <td>
                <form method="post">
                    <input type="hidden" name="selectedNum" value="<?php echo $this->escapeHtml($contact->contact_no);?>">
                    <input type="hidden" name="clickedDel" value="YES">
                    <input type="submit" value = "delete">
                </form>
            </td>

        </tr>
    <?php endforeach; ?>
    <tr><td>
            <form method="post">
                <input type="text" name="contact">
        </td><td>
            <input class="btn btn-primary btn-sm" type="submit" name="saveClicked" value = "Save">
            </form>
        </td>
    </tr>
</table>