<?php
// module/Album/view/album/album/index.phtml:

$title = 'Registered Persional Representative';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9"><h1><?php echo $this->escapeHtml($title); ?></h1></div>


    <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
        <h1>
            <a href="<?php echo $this->url('psr', array('action' => 'add')); ?>"><input type="button"
                                                                                             class="btn btn-primary btn-lg pull-right btn-block"
                                                                                             value="Add New"></a></h1>
    </div>
</div>

<table class="table table-striped">
    <tr>
        <th>emp_id</th>
        <th>name</th>
        <th>po_box</th>
        <th>street</th>
        <th>city</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($psrs as $psr) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($psr->emp_id);?></td>
            <td><?php echo $this->escapeHtml($psr->name);?></td>
            <td><?php echo $this->escapeHtml($psr->po_box);?></td>
            <td><?php echo $this->escapeHtml($psr->street);?></td>
            <td><?php echo $this->escapeHtml($psr->city);?></td>
            <td class="text-right">
                <a href="<?php echo $this->url('psr',
                    array('action'=>'edit', 'id' => $psr->emp_id));?>"><input type="button"
                                                                              class="btn btn-xs btn-default"
                                                                              value="Edit"></a>
                <a href="<?php echo $this->url('psr',
                    array('action'=>'delete', 'id' => $psr->emp_id));?>"><input type="button"
                                                                                class="btn btn-xs btn-default"
                                                                                value="Delete"></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>