<?php
// module/Album/view/album/album/index.phtml:

$title = 'One Stop Shop';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<ul class="nav">
    <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
    <li class="active"><a href="<?php echo $this->url('business') ?>"><?php echo $this->translate('Business') ?></a></li>
    <li class="active"><a href="<?php echo $this->url('customer') ?>"><?php echo $this->translate('Customer') ?></a></li>
    <li class="active"><a href="<?php echo $this->url('item') ?>"><?php echo $this->translate('Item') ?></a></li>

</ul>