<?php
// module/Album/view/album/album/index.phtml:

$title = 'Home';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>
<div class="col-md-4">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#business">
                        Businesses
                    </a>
                </h4>
            </div>
            <div id="business" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="nav">
                        <li class="active"><a
                                href="<?php echo $this->url('business') ?>"><?php echo $this->translate('Show Business') ?></a>
                        </li>
                        <li class="active"><a
                                href="<?php echo $this->url('business', array('action' => 'add')) ?>"><?php echo $this->translate('Add Business') ?></a>
                        </li>


                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#customer">
                        Customers
                    </a>
                </h4>
            </div>
            <div id="customer" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="nav">

                        <li class="active"><a
                                href="<?php echo $this->url('customer') ?>"><?php echo $this->translate('Show Customer') ?></a>
                        </li>
                        <li class="active"><a
                                href="<?php echo $this->url('customer', array('action' => 'add')) ?>"><?php echo $this->translate('Add Customer') ?></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#item">
                        Items
                    </a>
                </h4>
            </div>
            <div id="item" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="nav">

                        <li class="active"><a
                                href="<?php echo $this->url('item') ?>"><?php echo $this->translate('Show Item') ?></a>
                        </li>
                        <li class="active"><a
                                href="<?php echo $this->url('item', array('action' => 'add')) ?>"><?php echo $this->translate('Add Item') ?></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#psr">
                        Personal Sales Representatives
                    </a>
                </h4>
            </div>
            <div id="psr" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="nav">

                        <li class="active"><a
                                href="<?php echo $this->url('psr') ?>"><?php echo $this->translate('Show Personal Sales Representatives') ?></a>
                        </li>

                        <li class="active"><a
                                href="<?php echo $this->url('psr', array('action' => 'add')) ?>"><?php echo $this->translate('Add New Personal Sales Representative') ?></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#order">
                        Orders
                    </a>
                </h4>
            </div>
            <div id="order" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="nav">

                        <li class="active"><a
                                href="<?php echo $this->url('order') ?>"><?php echo $this->translate('Show Orders') ?></a>
                        </li>

                        <li class="active"><a
                                href="<?php echo $this->url('order', array('action' => 'add')) ?>"><?php echo $this->translate('Create New Order') ?></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-8">

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="<?php echo $this->basePath() . '/img/one.jpg' ?>" class="img-responsive" height="250">
            </div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/two.jpg' ?>" height="250"></div>
            <div class="item">
                <img src="<?php echo $this->basePath() . '/img/three.jpg' ?> "class="img-responsive" height="250"></div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>


    <h1 class="text-center">One Stop Shop<br>
        <small>On Your Way Home | ගෙදර යන ගමන් |வீடு செல்லும் போது</small>
    </h1>


</div>
