<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Business';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<body>
<div class="container">

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'business',
        array(
            'action' => 'add'
        )
    ));
    $form->prepare();

    echo $this->form()->openTag($form);?>
    <div class="panel panel-default">
        <div class="panel-body">
            <div><?php echo $this->formRow($form->get('brn')); ?></div>
            <div> <?php echo $this->formRow($form->get('name')); ?></div>
            <div> <?php echo $this->formSubmit($form->get('submit')); ?></div>
        </div>
    </div>




    <?php echo $this->form()->closeTag(); ?>
</div>
</body>