<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Business';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<body>
<div class="container">

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('business', array('action' => 'add')));
    $form->prepare();?>

<form class="form-control">
    <?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('brn'));
    echo $this->formRow($form->get('name'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag(); ?>
</form>
</div>
</body>