<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add New Business';
$this->headTitle($title);
?>


<body>
<div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <div class="col-lg-8 col-md-8 col-lg-push-2 col-md-push-2">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url(
            'business',
            array(
                'action' => 'add'
            )
        ));
        $form->prepare();

        echo $this->form()->openTag($form);?>
        <div class="panel panel-default">
            <div class="panel-body">
                <div><?php echo $this->formRow($form->get('brn')); ?></div>
                <div> <?php echo $this->formRow($form->get('name')); ?></div>
                <div class="text-right"> <?php echo $this->formSubmit($form->get('submit')); ?></div>
            </div>
        </div>




        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
</body>
