<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete business';
$this->headTitle($title);
?>


<div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Are you sure that you want to delete
        <b>'<?php echo $this->escapeHtml($business->name); ?>'</b>?
    </p>
    <?php
    $url = $this->url('business', array(
        'action' => 'delete',
        'id' => $this->brn,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <table class="table table-striped ">
                <tr><div class="col-md-push-5 col-lg-push-5">
                    <input class="btn btn-danger" type="submit" name="del" value="Yes"/>
                    &nbsp;
                    <input class="btn btn-default" type="submit" name="del" value="No"/>
                    &nbsp;
                    </div></tr>
            </table>
        </div>
    </form>
</div>