<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete business';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($business->brn); ?>' by
    '<?php echo $this->escapeHtml($business->name); ?>'?
</p>
<?php
$url = $this->url('business', array(
    'action' => 'delete',
    'id'     => $this->brn,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <table class="table table-striped ">
            <tr>
                <input class="alert-success" type="submit" name="del" value="Yes" />
        &nbsp;
                <input class="alert-danger" type="submit" name="del" value="No" />
        &nbsp;
            </tr>
    </div>
</form>