<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit business';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'business',
    array(
        'action' => 'edit',
        'id'     => $this->brn,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo '<b>Brn: </b>'.$this->brn."<br>";
echo $this->formHidden($form->get('brn'));
echo $this->formRow($form->get('name'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();