<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit business';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'business',
    array(
        'action' => 'edit',
        'id' => $this->brn,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo '<b>Brn: </b>'.$this->brn."<br>";
echo $this->formHidden($form->get('brn'));
echo $this->formRow($form->get('name'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();?>

<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#contact">
    Add Tp
</button>

<!-- Modal -->
<div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">New Contact Number</h4>

            </div>
            <form method="post">
                <div class="modal-body">
                    Contact Number : <input type="text" name="contact">
                    <input type="hidden" name="clicked" value="YES">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary"  value="save">
                </div>
            </form>
        </div>
    </div>
</div>


