<?php
// module/Album/view/album/album/index.phtml:

$title = 'Registered Businesses';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('business', array('action'=>'add'));?>"><input class="btn btn-primary" value="Add New Business"></a>
</p>


<table class="table">
    <tr>
        <th>brn</th>
        <th>name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($businesses as $business) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($business->brn);?></td>
            <td><?php echo $this->escapeHtml($business->name);?></td>
            <td>
                <a href="<?php echo $this->url('business',
                    array('action'=>'edit', 'id' => $business->brn));?>">Edit</a>
                <a href="<?php echo $this->url('business',
                    array('action'=>'delete', 'id' => $business->brn));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>