<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new order';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('order', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('order_no'));
echo $this->formRow($form->get('order_type'));
echo $this->formRow($form->get('date'));
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('cid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();