<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($order->order_no); ?>' by
    '<?php echo $this->escapeHtml($order->date); ?>'?
</p>
<?php
$url = $this->url('order', array(
    'action' => 'delete',
    'id'     => $this->order_no,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>