<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit order';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'order',
    array(
        'action' => 'edit',
        'id'     => $this->order_no,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('order_no'));
echo $this->formRow($form->get('date'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();