<?php
// module/Album/view/album/album/index.phtml:

$title = 'Registered Orders';
$this->headTitle($title);
?>
<html>
<body>
<div class="container col-lg-10 col-md-10 col-lg-push-1 col-md-push-1">
    <div class="row">
        <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9"><h1><?php echo $this->escapeHtml($title); ?></h1></div>
        <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
            <h1>
                <a href="<?php echo $this->url('order', array('action' => 'add')); ?>"><input type="button"
                                                                                              class="btn btn-primary btn-lg pull-right btn-block"
                                                                                              value="Add New"></a></h1>
        </div>
    </div>
    <table class="table table-striped">
        <?php foreach ($orders as $order) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($order->order_no);?></td>
                <td><?php echo $this->escapeHtml($order->date);?></td>
                <td class="text-right">
                    <a href="<?php echo $this->url('order',
                        array('action'=>'view', 'id' => $order->order_no));?>"><input type="button"
                                                                                      class="btn btn-xs btn-default"
                                                                                      value="View"></a>

                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
</body>
</html>
