<?php
// module/Album/view/album/album/index.phtml:

$title = 'Registered Orders';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9"><h1><?php echo $this->escapeHtml($title); ?></h1></div>


    <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
        <h1>
            <a href="<?php echo $this->url('order', array('action' => 'add')); ?>"><input type="button"
                                                                                        class="btn btn-primary btn-lg pull-right btn-block"
                                                                                        value="Add New"></a></h1>
    </div>
</div>
<table class="table table-striped">
    <tr>
        <th>order_no</th>
        <th>date</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($orders as $order) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($order->order_no);?></td>
            <td><?php echo $this->escapeHtml($order->date);?></td>
            <td class="text-right">
                <a href="<?php echo $this->url('order',
                    array('action'=>'edit', 'id' => $order->order_no));?>"><input type="button"
                                                                                  class="btn btn-xs btn-default"
                                                                                  value="Edit"></a>

            </td>
        </tr>
    <?php endforeach; ?>
</table>