<?php

$title = 'View Order '.$id;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br>
<table class="table table-striped">
    <tr><th>Items</th><td></td></tr>
    <?php foreach ($current as $item) : ?>

        <tr>
            <td><?php echo $this->escapeHtml($item->name); ?></td>
            <td>
                <?php echo $this->escapeHtml($item->quantity); ?>
            </td>

        </tr>
    <?php endforeach; ?>
</table>
<form method="post">
    <input class="btn btn-primary btn-sm" type="submit" name="done" value = "Done">
</form>